# Generated by Django 5.2.2 on 2025-06-23 21:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='actual_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual distance traveled', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='actual_duration',
            field=models.IntegerField(blank=True, help_text='Actual duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='alix_route_reference',
            field=models.CharField(blank=True, help_text='ALIX system reference', max_length=100),
        ),
        migrations.AddField(
            model_name='route',
            name='assigned_vehicle_type',
            field=models.CharField(blank=True, help_text='Type of vehicle assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='route',
            name='co2_emissions',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CO2 emissions in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='electronic_log_data',
            field=models.JSONField(blank=True, default=dict, help_text='Data from electronic truck logs'),
        ),
        migrations.AddField(
            model_name='route',
            name='fuel_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel consumed in liters', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='gps_tracking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='route',
            name='km_per_tonne',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='KM/TM efficiency metric', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='planned_during_week',
            field=models.CharField(blank=True, help_text='Week when route was planned (e.g., 2024-W45)', max_length=10),
        ),
        migrations.AddField(
            model_name='route',
            name='planning_accuracy_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('90.0'), help_text='Target accuracy percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='route',
            name='route_efficiency_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall route efficiency percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='route_type',
            field=models.CharField(blank=True, choices=[('contract', 'Contract Deliveries'), ('on_demand', 'On-Demand Deliveries'), ('emergency', 'Emergency Refills'), ('mixed', 'Mixed Route')], default='mixed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='total_capacity_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total capacity used in tonnes', max_digits=10),
        ),
        migrations.AddField(
            model_name='routeoptimization',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routeoptimization',
            name='distance_savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='routeoptimization',
            name='estimated_co2_reduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='routeoptimization',
            name='estimated_fuel_savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='routeoptimization',
            name='external_service_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='routeoptimization',
            name='google_maps_used',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routeoptimization',
            name='optimization_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall optimization score', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='routeoptimization',
            name='optimized_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='routeoptimization',
            name='optimized_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routeoptimization',
            name='original_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='routeoptimization',
            name='original_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routeoptimization',
            name='time_savings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='actual_departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='actual_service_time',
            field=models.IntegerField(blank=True, help_text='Actual service time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='customer_signature_captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routestop',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('silo_to_silo', 'Silo to Silo (Bulk)'), ('compartment_delivery', 'Tank Compartment'), ('tote_delivery', 'Tote Bags')], default='silo_to_silo', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='delivery_rating',
            field=models.IntegerField(blank=True, help_text='Customer rating 1-5', null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='estimated_service_time',
            field=models.IntegerField(default=30, help_text='Estimated service time in minutes'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='had_delivery_issues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routestop',
            name='issue_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='quantity_delivered',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual quantity delivered', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='quantity_to_deliver',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Planned quantity in tonnes', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='optimized_sequence',
            field=models.JSONField(default=list, help_text='Optimized delivery sequence'),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='routeoptimization',
            name='optimization_type',
            field=models.CharField(choices=[('distance', 'Minimize Distance'), ('duration', 'Minimize Duration'), ('fuel_cost', 'Minimize Fuel Cost'), ('balanced', 'Balanced Optimization'), ('co2_emissions', 'Minimize CO2 Emissions')], default='balanced', max_length=20),
        ),
        migrations.AlterField(
            model_name='routeoptimization',
            name='request_data',
            field=models.JSONField(help_text='Request sent to optimization service'),
        ),
        migrations.AlterField(
            model_name='routeoptimization',
            name='response_data',
            field=models.JSONField(help_text='Response from optimization service'),
        ),
        migrations.CreateModel(
            name='MonthlyRoutePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('total_routes_month', models.IntegerField(default=0)),
                ('total_distance_month', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_quantity_month', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_km_per_tonne_trituro_44', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('monthly_km_per_tonne_dairy_trituro', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('monthly_km_per_tonne_oil', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('planning_accuracy_1_week', models.DecimalField(blank=True, decimal_places=2, help_text='1 week planning accuracy (90-95% target)', max_digits=5, null=True)),
                ('planning_accuracy_1_month', models.DecimalField(blank=True, decimal_places=2, help_text='1 month planning accuracy (80-85% target)', max_digits=5, null=True)),
                ('planning_accuracy_3_months', models.DecimalField(blank=True, decimal_places=2, help_text='3 month planning accuracy (80-85% target)', max_digits=5, null=True)),
                ('monthly_co2_emissions', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sustainability_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('compared_to_previous_month', models.CharField(blank=True, choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=20, null=True)),
                ('meets_monthly_targets', models.BooleanField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('calculated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyRoutePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Monday of the week')),
                ('week_end_date', models.DateField(help_text='Sunday of the week')),
                ('total_routes_planned', models.IntegerField(default=0)),
                ('total_routes_completed', models.IntegerField(default=0)),
                ('total_routes_cancelled', models.IntegerField(default=0)),
                ('total_distance_planned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_distance_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_quantity_delivered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('km_per_tonne_trituro_44', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('km_per_tonne_dairy_trituro', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('km_per_tonne_oil', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_fuel_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_co2_emissions', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('planning_accuracy_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('on_time_delivery_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('customer_satisfaction_average', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('fleet_utilization_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vehicle_breakdown_by_type', models.JSONField(default=dict, help_text='Usage breakdown by vehicle type')),
                ('meets_90_percent_accuracy_target', models.BooleanField(blank=True, null=True)),
                ('exceeds_kpi_targets', models.BooleanField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('calculated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('week_start_date', 'week_end_date')},
            },
        ),
    ]
