# Generated by Django 5.2.2 on 2025-06-23 21:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedstorage',
            name='low_stock_threshold',
        ),
        migrations.AddField(
            model_name='farmer',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_farmers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmer',
            name='alix_customer_id',
            field=models.CharField(blank=True, help_text='ALIX customer ID', max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='client_type',
            field=models.CharField(blank=True, choices=[('dairy_trituro', 'Dairy Trituro'), ('trituro_44', 'Trituro 44'), ('oil', 'Oil'), ('other', 'Other')], default='dairy_trituro', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='has_contract',
            field=models.BooleanField(default=False, help_text='Has long-term contract'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='historical_monthly_usage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Average monthly usage in tonnes', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='preferred_delivery_day',
            field=models.CharField(blank=True, help_text='Preferred delivery day of week', max_length=10),
        ),
        migrations.AddField(
            model_name='farmer',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='province',
            field=models.CharField(blank=True, choices=[('QC', 'Quebec'), ('ON', 'Ontario'), ('NB', 'New Brunswick'), ('BC', 'British Columbia'), ('USD', 'United States'), ('SPAIN', 'Spain')], default='QC', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='zoho_crm_id',
            field=models.CharField(blank=True, help_text='ZOHO CRM client ID', max_length=100),
        ),
        migrations.AddField(
            model_name='feedstorage',
            name='is_connected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedstorage',
            name='last_maintenance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedstorage',
            name='low_stock_threshold_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('80.0'), max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='feedstorage',
            name='low_stock_threshold_tonnes',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1.0'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feedstorage',
            name='reporting_frequency',
            field=models.IntegerField(blank=True, default=60, help_text='Reporting frequency in minutes', null=True),
        ),
        migrations.AddField(
            model_name='feedstorage',
            name='sensor_type',
            field=models.CharField(blank=True, choices=[('binconnect', 'BinConnect'), ('manual', 'Manual Entry'), ('other', 'Other Sensor')], default='binconnect', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='alix_order_id',
            field=models.CharField(blank=True, help_text='ALIX sales order ID', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('bulk_38tm', 'Bulk Truck (38 tm)'), ('tank_compartment', 'Tank Compartments (2-10 tm)'), ('tote_500kg', 'Tote Bags 500kg'), ('tote_1000kg', 'Tote Bags 1000kg')], default='bulk_38tm', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expedition_number',
            field=models.CharField(blank=True, help_text='System-generated expedition number', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='forecast_based',
            field=models.BooleanField(default=False, help_text='Generated from consumption forecast'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('contract', 'Contract Delivery'), ('on_demand', 'On-Demand'), ('emergency', 'Emergency Refill'), ('proactive', 'Proactive Based on Forecast')], default='on_demand', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='planning_week',
            field=models.CharField(blank=True, help_text='Planning week (e.g., 2024-W45)', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedstorage',
            name='capacity',
            field=models.DecimalField(decimal_places=2, help_text='Total capacity in tonnes (3-80 tm range)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='feedstorage',
            name='current_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Current quantity in tonnes', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity in tonnes', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('planned', 'Planned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
