# Generated by Django 5.2.2 on 2025-09-02 19:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_feedstorage_low_stock_threshold_and_more'),
        ('driver', '0002_vehicle_remove_deliveryitem_delivered_quantity_and_more'),
        ('route', '0002_route_actual_distance_route_actual_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='driver.driver'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='route.route'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='driver.vehicle'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Marked as urgent by system or user'),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Requires manager approval'),
        ),
        migrations.AlterField(
            model_name='feedstorage',
            name='low_stock_threshold_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('20.0'), max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'expected_delivery_date'], name='clients_ord_status_d5437a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['farmer', 'status'], name='clients_ord_farmer__db756d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['priority', 'is_urgent'], name='clients_ord_priorit_02389d_idx'),
        ),
    ]
