# Generated by Django 5.2.2 on 2025-06-23 21:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bulk_truck', 'Bulk Truck'), ('tank_oil', 'Oil Tank'), ('tank_blower', 'Blower Compartment Tank'), ('box_truck', 'Box Truck (Tote Bags)'), ('dump_truck', 'Dump Truck')], max_length=20)),
                ('capacity_tonnes', models.DecimalField(decimal_places=2, help_text='Vehicle capacity in tonnes', max_digits=8)),
                ('make_model', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('has_gps_tracking', models.BooleanField(default=False)),
                ('electronic_log_device', models.CharField(blank=True, help_text='Electronic truck log device ID', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'In Maintenance'), ('out_of_service', 'Out of Service')], default='active', max_length=20)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('next_maintenance_due', models.DateTimeField(blank=True, null=True)),
                ('odometer_km', models.IntegerField(default=0, help_text='Current odometer reading in KM')),
                ('fuel_efficiency_l_per_100km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('co2_emissions_factor', models.DecimalField(decimal_places=4, default=Decimal('2.31'), help_text='CO2 kg per liter of diesel', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vehicle_type', 'vehicle_number'],
            },
        ),
        migrations.RemoveField(
            model_name='deliveryitem',
            name='delivered_quantity',
        ),
        migrations.RemoveField(
            model_name='deliveryitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='delivery',
            name='actual_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='actual_duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='co2_emissions_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='fuel_consumed_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='gps_tracking_data',
            field=models.JSONField(blank=True, default=dict, help_text='GPS data from electronic truck log'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='customer_rating',
            field=models.IntegerField(blank=True, help_text='1-5 rating from customer', null=True),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='delivery_confirmation_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('silo_to_silo', 'Silo to Silo (Bulk)'), ('compartment_unload', 'Tank Compartment Unload'), ('tote_delivery', 'Tote Bag Delivery')], default='silo_to_silo', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='quality_check_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='quantity_delivered',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual delivered quantity in tonnes', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='quantity_planned',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Planned quantity in tonnes', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='average_delivery_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='can_drive_vehicle_types',
            field=models.JSONField(default=list, help_text='List of vehicle types this driver is certified for'),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_deliveries_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_km_driven',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='total_quantity_delivered',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total delivered in tonnes', max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='signature',
            field=models.TextField(blank=True, help_text='Base64 encoded signature', null=True),
        ),
        migrations.CreateModel(
            name='DeliveryPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20)),
                ('product_type', models.CharField(choices=[('all_trituro_44', 'All Trituro 44'), ('all_dairy_trituro', 'All Dairy Trituro'), ('all_oil', 'All Oil'), ('combined', 'Combined')], max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_km', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tonnes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('km_per_tonne', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('total_co2_emissions_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_delivery_time_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('on_time_delivery_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('metric_type', 'product_type', 'period_start', 'period_end')},
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='driver.vehicle'),
        ),
        migrations.AddField(
            model_name='driver',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drivers', to='driver.vehicle'),
        ),
    ]
